apiVersion: v1
kind: Service
metadata:
  name: jenkins-slave-svc
  namespace: devops-tools
spec:
  selector:
    app: jenkins-slave
  type: ClusterIP 
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22